name: 'AumOS Compliance Check'
description: 'Check AI agent compliance against EU AI Act, GDPR, HIPAA, SOC 2 frameworks'
branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  framework:
    description: 'Compliance framework: eu-ai-act, gdpr, hipaa, soc2, all'
    required: false
    default: 'all'
  policy-path:
    description: 'Path to governance policy YAML'
    required: false
    default: 'governance-policy.yaml'
  python-version:
    description: 'Python version'
    required: false
    default: '3.12'
  fail-on-violation:
    description: 'Fail workflow on compliance violations'
    required: false
    default: 'true'
  risk-level:
    description: 'EU AI Act risk classification: minimal, limited, high, unacceptable'
    required: false
    default: 'high'

outputs:
  compliant:
    description: 'Whether the project is compliant'
    value: ${{ steps.check.outputs.compliant }}
  violations:
    description: 'Number of compliance violations'
    value: ${{ steps.check.outputs.violations }}
  report-path:
    description: 'Path to compliance report'
    value: ${{ steps.check.outputs.report }}

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install agent-gov
      shell: bash
      run: pip install agent-gov

    - name: Run compliance check
      id: check
      shell: bash
      run: |
        ARGS="--format json --output compliance-report.json"
        if [ "${{ inputs.framework }}" != "all" ]; then
          ARGS="$ARGS --framework ${{ inputs.framework }}"
        fi
        if [ -f "${{ inputs.policy-path }}" ]; then
          ARGS="$ARGS --policy ${{ inputs.policy-path }}"
        fi
        if [ "${{ inputs.risk-level }}" != "" ]; then
          ARGS="$ARGS --risk-level ${{ inputs.risk-level }}"
        fi

        EXIT_CODE=0
        agent-gov check $ARGS || EXIT_CODE=$?

        echo "report=compliance-report.json" >> $GITHUB_OUTPUT
        if [ -f compliance-report.json ]; then
          VIOLATIONS=$(python -c "import json; r=json.load(open('compliance-report.json')); print(r.get('violations', 0))")
          echo "violations=$VIOLATIONS" >> $GITHUB_OUTPUT
          echo "compliant=$( [ $VIOLATIONS -eq 0 ] && echo 'true' || echo 'false' )" >> $GITHUB_OUTPUT
        else
          echo "violations=0" >> $GITHUB_OUTPUT
          echo "compliant=true" >> $GITHUB_OUTPUT
        fi

        if [ "${{ inputs.fail-on-violation }}" = "true" ] && [ $EXIT_CODE -ne 0 ]; then
          exit 1
        fi

    - name: Upload compliance report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: compliance-report
        path: compliance-report.json
        if-no-files-found: ignore
